### ISSUE TITLE
's' key keeping its usual Vim binding.

### ISSUE THREAD

**Issue by capn-freako** [isovector/ghci.vim#6]
I've added your Vim plugin, by adding this line to my _.vimrc_ file:

`Plug 'isovector/ghci.vim'
`

inside my `plug#begin` / `plug#end` block.

But, the 's' key is doing its normal Vim thing: dropping me into INSERT mode, after deleting the character under the cursor.

How can I debug this?

**Comment by isovector** [comment]
I changed the prefix to `z` at some point -- apparently without updating the documentation :)

https://github.com/isovector/ghci.vim/blob/master/plugin/ghci.vim#L1-L10

**Comment by capn-freako** [comment]
Okay, learned some things:

1. You must run `:PlugInstall`, from within Vim, after updating the Vim configurations file(s) with additional plug-ins, in order to trigger the fetch from GitHub and subsequent installation into the _bundle_ directory. Done.

1. You can use `:scriptnames` to confirm loading of a particular plug-in. Doing this, I do see the _ghci.vim_ plug-in being loaded:

    > 63: ~/.config/haskell-vim-now/.vim/bundle/ghci.vim/plugin/ghci.vim

**Comment by capn-freako** [comment]
Okay, thanks.
